In [2]:
import pandas as pd

In [3]:
# Dataframes for movie and oscar data
movie_df = pd.read_csv("Cleaned_IMDB_Data.csv")
oscar_df = pd.read_csv("oscar_data.csv")

In [4]:
# Many movies had missing entries for the names, dropped those because we cant use that data.
oscar_df_cleaned = oscar_df.dropna()

In [5]:
print(len(oscar_df))

10867

In [6]:
print(len(oscar_df_cleaned))

10558

In [7]:
oscar_df_cleaned

,ceremony_year,ceremony,award_category,name,film,status
0,2024,96th,Actor In a Leading Role,Cillian Murphy,Oppenheimer,Won
1,2024,96th,Actor In a Supporting Role,Robert Downey Jr.,Oppenheimer,Won
2,2024,96th,Actress In a Leading Role,Emma Stone,Poor Things,Won
3,2024,96th,Actress In a Supporting Role,Da'Vine Joy Randolph,The Holdovers,Won
4,2024,96th,Animated Feature Film,The Boy and the Heron,Hayao Miyazaki and Toshio Suzuki,Won
...,...,...,...,...,...,...
10858,1928,1st,Writing (Adaptation),Anthony Coldeway,Glorious Betsy,Nominated
10859,1928,1st,Writing (Adaptation),Benjamin Glazer,7th Heaven,Won
10860,1928,1st,Writing (Original Story),Lajos Biro,The Last Command,Nominated
10861,1928,1st,Writing (Original Story),Ben Hecht,Underworld,Won
10862,1928,1st,Writing (Title Writing),Gerald Duffy,The Private Life of Helen of Troy,Nominated

In [8]:
print(movie_df[movie_df["originalTitle"]=="7th Heaven"])

        titleID originalTitle  releaseYear  runtimeMinutes         genres  \
2663  tt0018379    7th Heaven         1927             110  Drama,Romance

      directors                                            writers  \
2663  nm0097648  nm0834944,nm0322227,nm0385012,nm0129721,nm0615868

      averageRating  numVotes           cast
2663            7.6    4100.0  ['nm0368237']

In [9]:
# Merging the dataframes over the movie titles to get the movie IDs for each award.
merged_df = pd.merge(oscar_df_cleaned, movie_df, left_on="film", right_on="originalTitle", how='left')

In [10]:
merged_df

,ceremony_year,ceremony,award_category,name,film,status,titleID,originalTitle,releaseYear,runtimeMinutes,genres,directors,writers,averageRating,numVotes,cast
0,2024,96th,Actor In a Leading Role,Cillian Murphy,Oppenheimer,Won,tt15398776,Oppenheimer,2023.0,180.0,"Biography,Drama,History",nm0634240,"nm0634240,nm3284831,nm2452558",8.4,650190.0,['nm3528716']
1,2024,96th,Actor In a Supporting Role,Robert Downey Jr.,Oppenheimer,Won,tt15398776,Oppenheimer,2023.0,180.0,"Biography,Drama,History",nm0634240,"nm0634240,nm3284831,nm2452558",8.4,650190.0,['nm3528716']
2,2024,96th,Actress In a Leading Role,Emma Stone,Poor Things,Won,tt14230458,Poor Things,2023.0,141.0,"Comedy,Drama,Romance",nm0487166,"nm1110111,nm1206865",8.4,102734.0,"['nm10606356', 'nm14930772', 'nm15182215', 'nm..."
3,2024,96th,Actress In a Supporting Role,Da'Vine Joy Randolph,The Holdovers,Won,tt14849194,The Holdovers,2023.0,133.0,"Comedy,Drama",nm0668247,nm0376003,8.0,103637.0,"['nm15201618', 'nm15201619', 'nm4782621']"
4,2024,96th,Animated Feature Film,The Boy and the Heron,Hayao Miyazaki and Toshio Suzuki,Won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15648,1928,1st,Writing (Original Story),Ben Hecht,Underworld,Won,tt0090233,Underworld,1985.0,92.0,"Action,Horror,Sci-Fi",nm0667767,"nm0000850,nm0135267",3.9,1193.0,['nm0201756']
15649,1928,1st,Writing (Original Story),Ben Hecht,Underworld,Won,tt0120414,Underworld,1996.0,95.0,"Comedy,Thriller",nm0002337,nm0084114,4.7,781.0,"['nm0030846', 'nm0543090', 'nm0900621']"
15650,1928,1st,Writing (Original Story),Ben Hecht,Underworld,Won,tt0135697,Underworld,1937.0,95.0,"Crime,Drama",nm0584778,"nm0048421,nm0584778",4.7,45.0,['nm0694064']
15651,1928,1st,Writing (Original Story),Ben Hecht,Underworld,Won,tt0320691,Underworld,2003.0,121.0,"Action,Fantasy,Thriller",nm0936482,"nm0340485,nm0936482,nm0564286",7.0,283622.0,"['nm1455547', 'nm1456417']"
15652,1928,1st,Writing (Title Writing),Gerald Duffy,The Private Life of Helen of Troy,Nominated,tt0017979,The Private Life of Helen of Troy,1927.0,87.0,"Action,Adventure,Comedy",nm0466099,"nm0259850,nm0792845,nm0933133,nm0240534,nm0732452",5.8,92.0,['nm0096476']

In [11]:
# Since movie names arent unique we also compare the year of release with the year the award was given, we keep the ones within a two year range.
condition_mask = ((merged_df["ceremony_year"] == merged_df["releaseYear"]) | (merged_df["ceremony_year"] == merged_df["releaseYear"] + 1)| (merged_df["ceremony_year"] == merged_df["releaseYear"] + 2))
filtered_df = merged_df[condition_mask]
filtered_df = filtered_df.drop(columns=["originalTitle", "releaseYear", "runtimeMinutes", "genres", "directors", "writers", "averageRating", "numVotes", "cast"])
filtered_df

,ceremony_year,ceremony,award_category,name,film,status,titleID
0,2024,96th,Actor In a Leading Role,Cillian Murphy,Oppenheimer,Won,tt15398776
1,2024,96th,Actor In a Supporting Role,Robert Downey Jr.,Oppenheimer,Won,tt15398776
2,2024,96th,Actress In a Leading Role,Emma Stone,Poor Things,Won,tt14230458
3,2024,96th,Actress In a Supporting Role,Da'Vine Joy Randolph,The Holdovers,Won,tt14849194
28,2024,96th,Actor In a Leading Role,Bradley Cooper,Maestro,Nominated,tt5535276
...,...,...,...,...,...,...,...
15643,1928,1st,Writing (Adaptation),Anthony Coldeway,Glorious Betsy,Nominated,tt0018945
15644,1928,1st,Writing (Adaptation),Benjamin Glazer,7th Heaven,Won,tt0018379
15645,1928,1st,Writing (Original Story),Lajos Biro,The Last Command,Nominated,tt0019071
15647,1928,1st,Writing (Original Story),Ben Hecht,Underworld,Won,tt0018526
15652,1928,1st,Writing (Title Writing),Gerald Duffy,The Private Life of Helen of Troy,Nominated,tt0017979

In [58]:
# We use the created merged dataframe to create new columns with the oscars won and ones nominated for in the movie dataframe.
oscars_count = filtered_df.pivot_table(index="titleID", columns="status", aggfunc="size", fill_value=0).reset_index()
final_df = pd.merge(movie_df, oscars_count, on="titleID", how="left")
final_df = final_df.rename(columns={'Won': 'Oscars Won', 'Nominated': "Oscar Nominations"})
final_df[['Oscars Won', "Oscar Nominations"]] = final_df[['Oscars Won', 'Oscar Nominations']].fillna(0).astype(int)
final_df

,titleID,originalTitle,releaseYear,runtimeMinutes,genres,directors,writers,averageRating,numVotes,cast,Oscar Nominations,Oscars Won
0,tt0000009,Miss Jerry,1894,45,Romance,nm0085156,nm0085156,5.3,208.0,['nm0063086'],0,0
1,tt0000574,The Story of the Kelly Gang,1906,70,"Action,Adventure,Biography",nm0846879,nm0846879,6.0,868.0,"['nm0170118', 'nm0187697', 'nm0511649', 'nm084...",0,0
2,tt0000591,L'enfant prodigue,1907,90,Drama,nm0141150,nm0141150,5.0,22.0,[],0,0
3,tt0000679,The Fairylogue and Radio-Plays,1908,120,"Adventure,Fantasy","nm0091767,nm0877783","nm0000875,nm0877783",5.0,70.0,"['nm0253055', 'nm0500744', 'nm0607349', 'nm093...",0,0
4,tt0000941,Locura de amor,1909,45,Drama,"nm0063413,nm0550220","nm0063413,nm0550220,nm0848502",4.5,27.0,"['nm0294022', 'nm0478718']",0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
241163,tt9916190,Safeguard,2020,95,"Action,Adventure,Thriller",nm7308376,nm7308376,3.6,254.0,"['nm10385419', 'nm11170357', 'nm11170358']",0,0
241164,tt9916270,Il talento del calabrone,2020,84,Thriller,nm1480867,"nm1480867,nm10538402",5.8,1474.0,[],0,0
241165,tt9916362,Akelarre,2020,92,"Drama,History",nm1893148,"nm1893148,nm3471432",6.4,5726.0,"['nm11957877', 'nm11957878', 'nm11957879', 'nm...",0,0
241166,tt9916538,Kuambil Lagi Hatiku,2019,123,Drama,nm4457074,"nm4843252,nm4900525,nm2679404",8.6,7.0,"['nm10538477', 'nm10538478', 'nm10538480', 'nm...",0,0
241167,tt9916730,6 Gunn,2017,116,Drama,nm10538612,nm10538612,7.0,12.0,[],0,0

In [60]:
print(final_df[final_df["originalTitle"] == "The Revenant"])

          titleID originalTitle  releaseYear  runtimeMinutes  \
142062  tt1336006  The Revenant         2009             117
158891  tt1663202  The Revenant         2015             156
195268  tt3300078  The Revenant         2012              80

                        genres  directors  \
142062   Comedy,Fantasy,Horror  nm0697934
158891  Action,Adventure,Drama  nm0327944
195268                  Horror  nm5419512

                                                  writers  averageRating  \
142062                                          nm0697934            6.3
158891                      nm1872664,nm0327944,nm3488559            8.0
195268  nm5419512,nm6053529,nm6053523,nm4866306,nm6053532            5.7

        numVotes                                               cast  \
142062   11283.0  ['nm5411761', 'nm5411764', 'nm5411779', 'nm541...
158891  866488.0  ['nm7506216', 'nm7618307', 'nm7818351', 'nm781...
195268      30.0  ['nm6053519', 'nm6053520', 'nm6053521', 'nm605...

        Oscar Nominations  Oscars Won
142062                  0           0
158891                  9           3
195268                  0           0

In [61]:
# Convert to csv.
final_df.to_csv("oscars_merged.csv", index=False)

In [15]:
print(merged_df.size)

250448